import { User, Promo, Reward, Activity } from './types';

export const MOCK_USER: User = {
  id: '1',
  name: 'Alex',
  studentId: '123456',
  points: 540,
  level: 'Elite Guardian',
  xp: 280,
  nextLevelXp: 400,
  impact: {
    cupsSaved: 54,
    plasticSavedKg: 2.7,
    co2SavedKg: 15,
  },
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8pe5WJG0tO9PlYelvY7vwSRp8Js0bwviyh7HHxm9Jy7NECfbDHFoidaB6o_Mv2mivBRYZCEhzVwm8lqwZxkAPvLLq-owGUKToTy4NtCjsM2DlVyC0bGOBDXThUSnHItqs3R7RgKGPHdeKbH0MJPRUrLO-PTqvziQP4QTneoRLKSmeIuO0tVnQiJTZq1a4oQV61UcM-POL9vHdXbNO6uDW0UQ-dB1hhh852RT3xyGCNjmh5Kp0Nfpvj754rI5mBM56E6p2uABixvk',
};

export const MOCK_PROMOS: Promo[] = [
  {
    id: 'p1',
    name: 'The Burger Joint',
    offer: '20% Off All Meals',
    distance: '0.4 km away',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAB_lUDn7tDrG35LzKLHLf_BfmyhCF8O_YGzV3S_loQyi3K-LO23ZiCyRnyaxmYfFkNlj_GjGzvqAwsDo38-q40P6G6goDWMCPfLB6kwiqydIchlSVXtiZgckmdMIfBU0uOQq7ZEmlUzT7im96-onYuM8gmIkD3oQo2OvGSBPo5ELd32W4Vm6c51UcMFUNCT18x3OMZGzciLeDMuBgvgXeMZUVweCRJLL0b7c89eFOgXDEq66sGuY5aCp8l22aN71Akjf_73nKbyaw',
    featured: true,
    category: 'Food',
  },
  {
    id: 'p2',
    name: 'Coffee House',
    offer: 'Buy 1 Get 1 Free Espresso',
    distance: '1.2 km away',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0sWRTiAMS08w1Zxmr0nDWNRgXxztT24XV4rJeL93ck7rpZlfFlH4u1_4W6UUn6ylk-uS1euXGIWguJyWPOeu9k4-Hr60XDNynlvpqOosUczDV8NDlX0WEj0fu3F-vwgKK6AYtd4HZ0qm0BTX6ZwAzZjfRcC_rxgmn_VAIcIUmniUD9ZbBX530n2F-q117LZrBjOptKkO-6WSgc_M4j2-2tE1zApF1_TaInNU7Y75xLoT3M-GDB9839Ny-8FH-NhoSpIt8qFIXYkA',
    category: 'Drinks',
  },
  {
    id: 'p3',
    name: 'Student Books',
    offer: '10% Student Discount',
    distance: '0.2 km away',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGY-Sr4w08CoCQ3nImmyTYmhpYWGace6ZOo3pFuYZ5eLLzBGKeY4YCwiG91R-4SjD6sw_le7820Xwucebzz67g3L2WZdPc03bjLdr3WvheY0UYcMnOK6st1Pz7yPeHXZYWxnSPoRsdpVd8U3KtJdSqKyzeuNWUb8DPjEV5iAG14sbOkhah7UnEslPi7MkW8NBsEkpxs1XP4zF8ojdaxoODr8wOHBSi2TGufPJyjnCr-lO22tC-BGmyIJVFKx5mIHEXcXmrMfeE03U',
    category: 'Retail',
  },
  {
    id: 'p4',
    name: 'Eco Laundry',
    offer: '50% Off First Load',
    distance: '2.5 km away',
    logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuABGl-xiVKRqsk8nNbewFG3zs3uiSjmUXgoa1w_FuxZabYPXgzKLtzUtMoFajvXlzkU5lD-bR7dVRoP3zo53RN4r1wjZQSEDY5H27Iwcgs8dMn3l7oqFf7gXcOpZ9Th1yZ4LqdUbu_vRB41EzlnLZL2ZVeEUPhX7dRwpk2e5yuViWAUbZgpCF9pFL_yp50UMFxUpMsm7nYAKUcbCv5wkAMfyPZdT2R3-BOxYsJmJn9XUSYFHNJNf75nXgDW6xkLJFiuwALxSwiyPbw',
    featured: true,
    category: 'Retail',
  },
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: 'r1',
    name: 'Free Espresso',
    category: 'BEVERAGE',
    points: 50,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAVVvYOVdIHgH2TJX8x6lHRXEUILb011AYRrPjuMeB_EwVq3av1h0H2FOhH6qLMWEgfMa9vg2Yu5wS4CT6GF8WO79aXfB9RMWZrZgI8GbCDMfjJ2fCMA0bo3mo_egP7FMT94UHvJUs0SSYYEL2BgJLZ0qyFOCk6Co4dU1iCMmjLmP9-6eON6I4MafbewLU3RO8CcKzfnegXQnxbv8snsFi2rNohJvhMIk_puq0MRNTJqT_AIuNXEoxc_O__5uieUBFHCrsLwDyhde8',
    vendorType: 'CAFETERIA',
    rewardType: 'FREE',
  },
  {
    id: 'r2',
    name: 'Pastel de Nata',
    category: 'BAKERY',
    points: 100,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8bdDL1boVcYNLF2U7Y5dUzoMhTGoh-TeJTYdJx6FHnYnKOq7m2OBZL-y6LagXP3XFuBB1oIzHe7woTMcKP66jNcrN-Kw4sjIlSCX6hBQPmv6HRCxbrE7m5pHmkCRmyIdhMc3fXndL0mXmxQLUfiXw9r66VMhZC9z0a7wpHssV4D1k6TcIJBWQr4vDn1JpZ6aQYJGse9wz99DXUoKqzm7XHilFIdiMcmLPk654X1zitxg5dBY7ZCq_K0K4eyNJMRdDznvDCL8b7lM',
    vendorType: 'CAFETERIA',
    rewardType: 'FREE',
  },
  {
    id: 'r3',
    name: 'Fresh Juice',
    category: 'BEVERAGE',
    points: 150,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5dEcjXUMNOeBsZOomTwJzRT-_bvdNG6PUqzx1tgCY66gcbSDVkXdXf7u_9KBan0oh-peuGENR5c7dXuUOeJ2zCpLeb3XUwS5f-oboLLMy7b6Uk9Vz696FVy6R1P0smshMyiyvoWHW_05akP_Y5T5CZ3uTm7qPlhEPcmNujK4sA1-1xPmyyDYpkXFb4cRV9h69lj64XtCot5elcxC_Daa0Gdxso6dEnGN2oCiqEwNSa1cR9K0s4Fs2xzCDi8d4N188av7KnoLXUmI',
    vendorType: 'CAFETERIA',
    rewardType: 'FREE',
  },
  {
    id: 'r4',
    name: 'Gourmet Sandwich',
    category: 'MEAL',
    points: 250,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8-2ZMBvzIrPjA1cntKK1m69gNgiNn0r5QXyswOkGCl7aiLplExRuvwDHoOd6A5-WKDhtKiauGhZgN4LWQZ7CoaVAKZ1aeC73qr7g_g9aZ3Xgr2F3EICxeFUg1bkwVwvZzd_ahvUhuMofR4PmTW1KCE9nRkAjdH50Efh5NAhadqqJqbONiqWGYPZQ4ZfbzFcn0hlOV7tQRbnuOxTNXhUtlUF03odV_yiJ39rjF3iQ4gEo65fOxZA1aWbX-mvwaUC0Ao0bwe_7Ca5A',
    vendorType: 'CAFETERIA',
    rewardType: 'FREE',
  },
  {
    id: 'r5',
    name: '20% Burger Discount',
    category: 'MEAL',
    points: 80,
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&q=80&w=400',
    vendorType: 'LOCAL_BUSINESS',
    rewardType: 'DISCOUNT',
  },
  {
    id: 'r6',
    name: 'Free Eco Tote Bag',
    category: 'RETAIL',
    points: 300,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=400',
    vendorType: 'LOCAL_BUSINESS',
    rewardType: 'FREE',
  },
  {
    id: 'r7',
    name: 'BOGO Coffee Promo',
    category: 'BEVERAGE',
    points: 40,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=400',
    vendorType: 'LOCAL_BUSINESS',
    rewardType: 'PROMO',
  },
  {
    id: 'r8',
    name: '10% Book Discount',
    category: 'RETAIL',
    points: 60,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400',
    vendorType: 'LOCAL_BUSINESS',
    rewardType: 'DISCOUNT',
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    type: 'return',
    title: 'Cup Returned',
    points: 10,
    date: 'Today, 10:45 AM',
    location: 'Cafeteria',
    description: 'You successfully returned a reusable cup at the main cafeteria. Thank you for helping reduce plastic waste!',
  },
  {
    id: 'a2',
    type: 'redeem',
    title: 'Free Espresso',
    points: -50,
    date: 'Yesterday, 4:20 PM',
    location: 'Bar',
    description: 'You redeemed 50 points for a free espresso at the Bar. Enjoy your sustainable caffeine boost!',
  },
  {
    id: 'a3',
    type: 'return',
    title: 'Cup Returned',
    points: 10,
    date: 'Oct 24, 09:15 AM',
    location: 'Building II',
    description: 'Cup returned at the Building II station. Your contribution helps save 0.05kg of plastic.',
  },
];
